# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1622a38dce454f1c1198d44de162af2b1ce8560e9e4c40d8a887822c1885aef013b08a7fa98a2ac648903d217fb689a9e8dd757fd6f6f2a6c5a497cb4270b32c

test:
  secret_key_base: d564067ebc320a3cbf07793c9fa732863f4537ff1b0bef9ff5c3f5782fd0afbe6c32029b01fcbe43f96aa7dd228da513ba6e3ee920fc99a48a41cc5ae0d59f47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
